### PR TITLE
Hover btns

### PR DESCRIPTION
**Pull request by Riul1999**
# Hover buttons
Added hover to buttons, reestructure buttons grid and add tittles to every image.

### `left_arrow.png` and `right_arrow.png` 
Images for Subir and Bajar buttons.

### `requirements.txt`
Added ttkwidgets to the requieres libraries to use the application, the library is used to generate the balloon text to describe the buttons.

### `src/img_tree.py`
Added field name to ImgNode.

### `src/utils.py`
- Added createBalloon function to generate a Balloon widget to display a message over a button, the message is displayed after1 second.
- Added createButtonWithHover function to create a Button and a Ballon with the specified name and description.
- Changed generate_zip to include the name of the files to create.

### `src/gui.py`
- Added file_fr, command_fr, crop_fr, size_fr, color_seg_fr, shape_seg_fr, image_tools_fr, gen_results_fr, navigate_fr and help_fr to creates menus to organize the buttons.
- Added description to buttons and displayed the description with text ballons, the descriptions are displayed after 1 second.
- Grided buttons acording to this [sketch](https://docs.google.com/presentation/d/1n0EDhqGUco3IuscnHnQsUqBRT-dKsu4T/edit#slide=id.p1).
- Displayed a label with the name of every image.
- Added help button, with a '?' icon. This button opens the documentation of the software, that is still in progress in this [link](https://www.overleaf.com/read/vxzxqrvghyyt).

### CODE REVIEW

**Comment by Magdalena-Alvarez** [comment]
Buttons are no longer responsive.

**Comment by Magdalena-Alvarez** [comment]
After merging, the help button link should be replaced with the document’s permalink in a permanent url.

**Comment by Magdalena-Alvarez** [comment]
- Buttons became responsive again.
- Fixed help button size.
- Fixed resize_img function.
- Modified navegate button, principal_fr and image_container position.

**Review by JorgeCVuwu — APPROVED** [review]

**Review by MisakaOneesama — APPROVED** [review]
Approved

**Review by Magdalena-Alvarez — APPROVED** [review]

**Pull request merged**
